-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lzw_compress_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    chunk_arr_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    chunk_arr_stream_empty_n : IN STD_LOGIC;
    chunk_arr_stream_read : OUT STD_LOGIC;
    codeword_stream_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    codeword_stream_full_n : IN STD_LOGIC;
    codeword_stream_write : OUT STD_LOGIC;
    gmem_load_loc_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    gmem_load_loc_empty_n : IN STD_LOGIC;
    gmem_load_loc_read : OUT STD_LOGIC );
end;


architecture behav of lzw_compress_stream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal chunk_arr_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_nbreadreq_fu_124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_i_i_reg_466 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal codeword_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal hit_fu_395_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_load_loc_blk_n : STD_LOGIC;
    signal gmem_load_loc_read_reg_437 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_56_fu_298_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln58_fu_315_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln64_fu_335_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_0_load_reg_491 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_2_reg_499 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_378_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln_reg_504 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln179_fu_387_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln179_reg_509 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_4_fu_431_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal assoc_mem_quarter_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal assoc_mem_quarter_0_ce0 : STD_LOGIC;
    signal assoc_mem_quarter_0_we0 : STD_LOGIC;
    signal assoc_mem_quarter_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_0_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal assoc_mem_quarter_1_ce0 : STD_LOGIC;
    signal assoc_mem_quarter_1_we0 : STD_LOGIC;
    signal assoc_mem_quarter_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_1_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal assoc_mem_quarter_2_ce0 : STD_LOGIC;
    signal assoc_mem_quarter_2_we0 : STD_LOGIC;
    signal assoc_mem_quarter_2_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_2_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal assoc_mem_quarter_3_ce0 : STD_LOGIC;
    signal assoc_mem_quarter_3_we0 : STD_LOGIC;
    signal assoc_mem_quarter_3_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_quarter_3_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal assoc_mem_value_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal assoc_mem_value_ce0 : STD_LOGIC;
    signal assoc_mem_value_we0 : STD_LOGIC;
    signal assoc_mem_value_d0 : STD_LOGIC_VECTOR (11 downto 0);
    signal assoc_mem_value_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal hash_table_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal hash_table_ce0 : STD_LOGIC;
    signal hash_table_we0 : STD_LOGIC;
    signal hash_table_d0 : STD_LOGIC_VECTOR (32 downto 0);
    signal hash_table_q0 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_lookup_and_insert_fu_280_ap_start : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_ap_done : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_ap_idle : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_ap_ready : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_hash_table_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_lookup_and_insert_fu_280_hash_table_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_hash_table_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_hash_table_d0 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_value_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_lookup_and_insert_fu_280_assoc_mem_value_ce0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_value_we0 : STD_LOGIC;
    signal grp_lookup_and_insert_fu_280_assoc_mem_value_d0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_lookup_and_insert_fu_280_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lookup_and_insert_fu_280_ap_return_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_lookup_and_insert_fu_280_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_reg_223 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal exitcond386_i_i_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_234 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln58_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_2_reg_245 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln64_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal assoc_mem_fill_0_i_i_reg_256 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state7 : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal i_3_reg_268 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lookup_and_insert_fu_280_ap_start_reg : STD_LOGIC := '0';
    signal ap_predicate_op81_read_state8 : BOOLEAN;
    signal ap_predicate_op87_write_state8 : BOOLEAN;
    signal ap_block_state8_ignore_call7 : BOOLEAN;
    signal p_cast_i_i_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_i_i_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_2_cast_i_i_fu_347_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0_fu_110 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln183_fu_392_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln172_fu_403_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln172_fu_352_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextCode_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal nextCode_1_fu_411_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal trunc_ln183_fu_374_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component lzw_lookup_and_insert IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hash_table_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        hash_table_ce0 : OUT STD_LOGIC;
        hash_table_we0 : OUT STD_LOGIC;
        hash_table_d0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        hash_table_q0 : IN STD_LOGIC_VECTOR (32 downto 0);
        assoc_mem_quarter_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        assoc_mem_quarter_0_ce0 : OUT STD_LOGIC;
        assoc_mem_quarter_0_we0 : OUT STD_LOGIC;
        assoc_mem_quarter_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        assoc_mem_quarter_1_ce0 : OUT STD_LOGIC;
        assoc_mem_quarter_1_we0 : OUT STD_LOGIC;
        assoc_mem_quarter_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        assoc_mem_quarter_2_ce0 : OUT STD_LOGIC;
        assoc_mem_quarter_2_we0 : OUT STD_LOGIC;
        assoc_mem_quarter_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        assoc_mem_quarter_3_ce0 : OUT STD_LOGIC;
        assoc_mem_quarter_3_we0 : OUT STD_LOGIC;
        assoc_mem_quarter_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_quarter_3_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        assoc_mem_value_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        assoc_mem_value_ce0 : OUT STD_LOGIC;
        assoc_mem_value_we0 : OUT STD_LOGIC;
        assoc_mem_value_d0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        assoc_mem_value_q0 : IN STD_LOGIC_VECTOR (11 downto 0);
        assoc_mem_fill_read : IN STD_LOGIC_VECTOR (31 downto 0);
        key : IN STD_LOGIC_VECTOR (19 downto 0);
        nextCode : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lzw_compress_stream_assoc_mem_quarter_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component lzw_compress_stream_assoc_mem_value IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (11 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component lzw_compress_stream_hash_table IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (32 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;



begin
    assoc_mem_quarter_0_U : component lzw_compress_stream_assoc_mem_quarter_0
    generic map (
        DataWidth => 64,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => assoc_mem_quarter_0_address0,
        ce0 => assoc_mem_quarter_0_ce0,
        we0 => assoc_mem_quarter_0_we0,
        d0 => assoc_mem_quarter_0_d0,
        q0 => assoc_mem_quarter_0_q0);

    assoc_mem_quarter_1_U : component lzw_compress_stream_assoc_mem_quarter_0
    generic map (
        DataWidth => 64,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => assoc_mem_quarter_1_address0,
        ce0 => assoc_mem_quarter_1_ce0,
        we0 => assoc_mem_quarter_1_we0,
        d0 => assoc_mem_quarter_1_d0,
        q0 => assoc_mem_quarter_1_q0);

    assoc_mem_quarter_2_U : component lzw_compress_stream_assoc_mem_quarter_0
    generic map (
        DataWidth => 64,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => assoc_mem_quarter_2_address0,
        ce0 => assoc_mem_quarter_2_ce0,
        we0 => assoc_mem_quarter_2_we0,
        d0 => assoc_mem_quarter_2_d0,
        q0 => assoc_mem_quarter_2_q0);

    assoc_mem_quarter_3_U : component lzw_compress_stream_assoc_mem_quarter_0
    generic map (
        DataWidth => 64,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => assoc_mem_quarter_3_address0,
        ce0 => assoc_mem_quarter_3_ce0,
        we0 => assoc_mem_quarter_3_we0,
        d0 => assoc_mem_quarter_3_d0,
        q0 => assoc_mem_quarter_3_q0);

    assoc_mem_value_U : component lzw_compress_stream_assoc_mem_value
    generic map (
        DataWidth => 12,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => assoc_mem_value_address0,
        ce0 => assoc_mem_value_ce0,
        we0 => assoc_mem_value_we0,
        d0 => assoc_mem_value_d0,
        q0 => assoc_mem_value_q0);

    hash_table_U : component lzw_compress_stream_hash_table
    generic map (
        DataWidth => 33,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hash_table_address0,
        ce0 => hash_table_ce0,
        we0 => hash_table_we0,
        d0 => hash_table_d0,
        q0 => hash_table_q0);

    grp_lookup_and_insert_fu_280 : component lzw_lookup_and_insert
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lookup_and_insert_fu_280_ap_start,
        ap_done => grp_lookup_and_insert_fu_280_ap_done,
        ap_idle => grp_lookup_and_insert_fu_280_ap_idle,
        ap_ready => grp_lookup_and_insert_fu_280_ap_ready,
        hash_table_address0 => grp_lookup_and_insert_fu_280_hash_table_address0,
        hash_table_ce0 => grp_lookup_and_insert_fu_280_hash_table_ce0,
        hash_table_we0 => grp_lookup_and_insert_fu_280_hash_table_we0,
        hash_table_d0 => grp_lookup_and_insert_fu_280_hash_table_d0,
        hash_table_q0 => hash_table_q0,
        assoc_mem_quarter_0_address0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_address0,
        assoc_mem_quarter_0_ce0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_ce0,
        assoc_mem_quarter_0_we0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_we0,
        assoc_mem_quarter_0_d0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_d0,
        assoc_mem_quarter_0_q0 => assoc_mem_quarter_0_q0,
        assoc_mem_quarter_1_address0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_address0,
        assoc_mem_quarter_1_ce0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_ce0,
        assoc_mem_quarter_1_we0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_we0,
        assoc_mem_quarter_1_d0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_d0,
        assoc_mem_quarter_1_q0 => assoc_mem_quarter_1_q0,
        assoc_mem_quarter_2_address0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_address0,
        assoc_mem_quarter_2_ce0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_ce0,
        assoc_mem_quarter_2_we0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_we0,
        assoc_mem_quarter_2_d0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_d0,
        assoc_mem_quarter_2_q0 => assoc_mem_quarter_2_q0,
        assoc_mem_quarter_3_address0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_address0,
        assoc_mem_quarter_3_ce0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_ce0,
        assoc_mem_quarter_3_we0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_we0,
        assoc_mem_quarter_3_d0 => grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_d0,
        assoc_mem_quarter_3_q0 => assoc_mem_quarter_3_q0,
        assoc_mem_value_address0 => grp_lookup_and_insert_fu_280_assoc_mem_value_address0,
        assoc_mem_value_ce0 => grp_lookup_and_insert_fu_280_assoc_mem_value_ce0,
        assoc_mem_value_we0 => grp_lookup_and_insert_fu_280_assoc_mem_value_we0,
        assoc_mem_value_d0 => grp_lookup_and_insert_fu_280_assoc_mem_value_d0,
        assoc_mem_value_q0 => assoc_mem_value_q0,
        assoc_mem_fill_read => assoc_mem_fill_0_i_i_reg_256,
        key => trunc_ln_reg_504,
        nextCode => trunc_ln179_reg_509,
        ap_return_0 => grp_lookup_and_insert_fu_280_ap_return_0,
        ap_return_1 => grp_lookup_and_insert_fu_280_ap_return_1,
        ap_return_2 => grp_lookup_and_insert_fu_280_ap_return_2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and ((tmp_i_i_reg_466 = ap_const_lv1_0) or ((icmp_ln179_fu_366_p2 = ap_const_lv1_0) or (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_lookup_and_insert_fu_280_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lookup_and_insert_fu_280_ap_start_reg <= ap_const_logic_0;
            else
                if ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (icmp_ln179_fu_366_p2 = ap_const_lv1_1) and (tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    grp_lookup_and_insert_fu_280_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lookup_and_insert_fu_280_ap_ready = ap_const_logic_1)) then 
                    grp_lookup_and_insert_fu_280_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    assoc_mem_fill_0_i_i_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                assoc_mem_fill_0_i_i_reg_256 <= grp_lookup_and_insert_fu_280_ap_return_2;
            elsif ((not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                assoc_mem_fill_0_i_i_reg_256 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    empty_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond386_i_i_fu_304_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_reg_223 <= empty_56_fu_298_p2;
            elsif ((not(((gmem_load_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                empty_reg_223 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    i_2_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i_2_reg_245 <= ap_const_lv7_0;
            elsif (((icmp_ln64_fu_341_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_2_reg_245 <= add_ln64_fu_335_p2;
            end if; 
        end if;
    end process;

    i_3_reg_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                i_3_reg_268 <= i_4_fu_431_p2;
            elsif ((not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                i_3_reg_268 <= ap_const_lv32_1;
            end if; 
        end if;
    end process;

    i_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_234 <= ap_const_lv6_0;
            elsif (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_reg_234 <= add_ln58_fu_315_p2;
            end if; 
        end if;
    end process;

    nextCode_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                nextCode_fu_114 <= ap_const_lv32_100;
            elsif ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                nextCode_fu_114 <= nextCode_1_fu_411_p2;
            end if; 
        end if;
    end process;

    p_0_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                p_0_fu_110 <= zext_ln172_fu_352_p1;
            elsif ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (hit_fu_395_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                p_0_fu_110 <= trunc_ln172_fu_403_p1;
            elsif ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                p_0_fu_110 <= zext_ln183_fu_392_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                gmem_load_loc_read_reg_437 <= gmem_load_loc_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln179_fu_366_p2 = ap_const_lv1_1) and (tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                p_0_load_reg_491 <= p_0_fu_110;
                tmp_V_2_reg_499 <= chunk_arr_stream_dout;
                trunc_ln179_reg_509 <= trunc_ln179_fu_387_p1;
                trunc_ln_reg_504 <= trunc_ln_fu_378_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                tmp_i_i_reg_466 <= grp_nbreadreq_fu_124_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, chunk_arr_stream_empty_n, codeword_stream_full_n, gmem_load_loc_empty_n, ap_CS_fsm_state7, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, tmp_i_i_reg_466, icmp_ln179_fu_366_p2, ap_CS_fsm_state9, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, grp_lookup_and_insert_fu_280_ap_done, grp_lookup_and_insert_fu_280_ap_return_1, exitcond386_i_i_fu_304_p2, icmp_ln58_fu_321_p2, icmp_ln64_fu_341_p2, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((gmem_load_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond386_i_i_fu_304_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln64_fu_341_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and ((tmp_i_i_reg_466 = ap_const_lv1_0) or ((icmp_ln179_fu_366_p2 = ap_const_lv1_0) or (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (icmp_ln179_fu_366_p2 = ap_const_lv1_1) and (tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln58_fu_315_p2 <= std_logic_vector(unsigned(i_reg_234) + unsigned(ap_const_lv6_1));
    add_ln64_fu_335_p2 <= std_logic_vector(unsigned(i_2_reg_245) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, gmem_load_loc_empty_n)
    begin
                ap_block_state1 <= ((gmem_load_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(chunk_arr_stream_empty_n, grp_nbreadreq_fu_124_p3)
    begin
                ap_block_state7 <= ((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0));
    end process;


    ap_block_state8_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
                ap_block_state8 <= (((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)));
    end process;


    ap_block_state8_ignore_call7_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
                ap_block_state8_ignore_call7 <= (((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)));
    end process;


    ap_block_state9_assign_proc : process(codeword_stream_full_n, grp_lookup_and_insert_fu_280_ap_return_1)
    begin
                ap_block_state9 <= ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, chunk_arr_stream_empty_n, codeword_stream_full_n, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, tmp_i_i_reg_466, icmp_ln179_fu_366_p2, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
        if ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and ((tmp_i_i_reg_466 = ap_const_lv1_0) or ((icmp_ln179_fu_366_p2 = ap_const_lv1_0) or (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op81_read_state8_assign_proc : process(grp_nbreadreq_fu_124_p3, tmp_i_i_reg_466, icmp_ln179_fu_366_p2)
    begin
                ap_predicate_op81_read_state8 <= ((icmp_ln179_fu_366_p2 = ap_const_lv1_1) and (tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op87_write_state8_assign_proc : process(grp_nbreadreq_fu_124_p3, tmp_i_i_reg_466, icmp_ln179_fu_366_p2)
    begin
                ap_predicate_op87_write_state8 <= (((icmp_ln179_fu_366_p2 = ap_const_lv1_0) and (tmp_i_i_reg_466 = ap_const_lv1_1)) or ((tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0)));
    end process;

    ap_ready <= internal_ap_ready;

    assoc_mem_quarter_0_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_address0, i_cast_i_i_fu_327_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_0_address0 <= i_cast_i_i_fu_327_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_0_address0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_address0;
        else 
            assoc_mem_quarter_0_address0 <= "XXXXX";
        end if; 
    end process;


    assoc_mem_quarter_0_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_0_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_0_ce0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_ce0;
        else 
            assoc_mem_quarter_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_0_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_0_d0 <= ap_const_lv64_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_0_d0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_d0;
        else 
            assoc_mem_quarter_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    assoc_mem_quarter_0_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_we0, icmp_ln58_fu_321_p2)
    begin
        if (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            assoc_mem_quarter_0_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_0_we0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_0_we0;
        else 
            assoc_mem_quarter_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_1_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_address0, i_cast_i_i_fu_327_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_1_address0 <= i_cast_i_i_fu_327_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_1_address0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_address0;
        else 
            assoc_mem_quarter_1_address0 <= "XXXXX";
        end if; 
    end process;


    assoc_mem_quarter_1_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_1_ce0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_ce0;
        else 
            assoc_mem_quarter_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_1_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_1_d0 <= ap_const_lv64_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_1_d0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_d0;
        else 
            assoc_mem_quarter_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    assoc_mem_quarter_1_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_we0, icmp_ln58_fu_321_p2)
    begin
        if (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            assoc_mem_quarter_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_1_we0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_1_we0;
        else 
            assoc_mem_quarter_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_2_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_address0, i_cast_i_i_fu_327_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_2_address0 <= i_cast_i_i_fu_327_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_2_address0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_address0;
        else 
            assoc_mem_quarter_2_address0 <= "XXXXX";
        end if; 
    end process;


    assoc_mem_quarter_2_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_2_ce0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_ce0;
        else 
            assoc_mem_quarter_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_2_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_2_d0 <= ap_const_lv64_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_2_d0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_d0;
        else 
            assoc_mem_quarter_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    assoc_mem_quarter_2_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_we0, icmp_ln58_fu_321_p2)
    begin
        if (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            assoc_mem_quarter_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_2_we0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_2_we0;
        else 
            assoc_mem_quarter_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_3_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_address0, i_cast_i_i_fu_327_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_3_address0 <= i_cast_i_i_fu_327_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_3_address0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_address0;
        else 
            assoc_mem_quarter_3_address0 <= "XXXXX";
        end if; 
    end process;


    assoc_mem_quarter_3_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_3_ce0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_ce0;
        else 
            assoc_mem_quarter_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_quarter_3_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            assoc_mem_quarter_3_d0 <= ap_const_lv64_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_3_d0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_d0;
        else 
            assoc_mem_quarter_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    assoc_mem_quarter_3_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state4, grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_we0, icmp_ln58_fu_321_p2)
    begin
        if (((icmp_ln58_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            assoc_mem_quarter_3_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_quarter_3_we0 <= grp_lookup_and_insert_fu_280_assoc_mem_quarter_3_we0;
        else 
            assoc_mem_quarter_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_value_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state6, grp_lookup_and_insert_fu_280_assoc_mem_value_address0, i_2_cast_i_i_fu_347_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            assoc_mem_value_address0 <= i_2_cast_i_i_fu_347_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_value_address0 <= grp_lookup_and_insert_fu_280_assoc_mem_value_address0;
        else 
            assoc_mem_value_address0 <= "XXXXXX";
        end if; 
    end process;


    assoc_mem_value_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state6, grp_lookup_and_insert_fu_280_assoc_mem_value_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            assoc_mem_value_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_value_ce0 <= grp_lookup_and_insert_fu_280_assoc_mem_value_ce0;
        else 
            assoc_mem_value_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    assoc_mem_value_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state6, grp_lookup_and_insert_fu_280_assoc_mem_value_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            assoc_mem_value_d0 <= ap_const_lv12_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_value_d0 <= grp_lookup_and_insert_fu_280_assoc_mem_value_d0;
        else 
            assoc_mem_value_d0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    assoc_mem_value_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state6, grp_lookup_and_insert_fu_280_assoc_mem_value_we0, icmp_ln64_fu_341_p2)
    begin
        if (((icmp_ln64_fu_341_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            assoc_mem_value_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            assoc_mem_value_we0 <= grp_lookup_and_insert_fu_280_assoc_mem_value_we0;
        else 
            assoc_mem_value_we0 <= ap_const_logic_0;
        end if; 
    end process;


    chunk_arr_stream_blk_n_assign_proc : process(chunk_arr_stream_empty_n, ap_CS_fsm_state7, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, tmp_i_i_reg_466, icmp_ln179_fu_366_p2)
    begin
        if ((((icmp_ln179_fu_366_p2 = ap_const_lv1_1) and (tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8)) or ((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            chunk_arr_stream_blk_n <= chunk_arr_stream_empty_n;
        else 
            chunk_arr_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    chunk_arr_stream_read_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, ap_CS_fsm_state7, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
        if (((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_predicate_op81_read_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8)) or (not(((grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (chunk_arr_stream_empty_n = ap_const_logic_0))) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            chunk_arr_stream_read <= ap_const_logic_1;
        else 
            chunk_arr_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    codeword_stream_blk_n_assign_proc : process(codeword_stream_full_n, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, tmp_i_i_reg_466, icmp_ln179_fu_366_p2, ap_CS_fsm_state9, grp_lookup_and_insert_fu_280_ap_return_1)
    begin
        if ((((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (((icmp_ln179_fu_366_p2 = ap_const_lv1_0) and (tmp_i_i_reg_466 = ap_const_lv1_1)) or ((tmp_i_i_reg_466 = ap_const_lv1_1) and (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0)))))) then 
            codeword_stream_blk_n <= codeword_stream_full_n;
        else 
            codeword_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    codeword_stream_din_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, ap_CS_fsm_state8, ap_CS_fsm_state9, p_0_load_reg_491, grp_lookup_and_insert_fu_280_ap_done, grp_lookup_and_insert_fu_280_ap_return_1, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8, p_0_fu_110)
    begin
        if ((not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            codeword_stream_din <= p_0_load_reg_491;
        elsif ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_predicate_op87_write_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            codeword_stream_din <= p_0_fu_110;
        else 
            codeword_stream_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    codeword_stream_write_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, ap_CS_fsm_state8, ap_CS_fsm_state9, grp_lookup_and_insert_fu_280_ap_done, grp_lookup_and_insert_fu_280_ap_return_1, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
        if (((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_predicate_op87_write_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state8)) or (not(((grp_lookup_and_insert_fu_280_ap_done = ap_const_logic_0) or ((grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (codeword_stream_full_n = ap_const_logic_0)))) and (grp_lookup_and_insert_fu_280_ap_return_1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            codeword_stream_write <= ap_const_logic_1;
        else 
            codeword_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_56_fu_298_p2 <= std_logic_vector(unsigned(empty_reg_223) + unsigned(ap_const_lv16_1));
    exitcond386_i_i_fu_304_p2 <= "1" when (empty_reg_223 = ap_const_lv16_8000) else "0";

    gmem_load_loc_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, gmem_load_loc_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_load_loc_blk_n <= gmem_load_loc_empty_n;
        else 
            gmem_load_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gmem_load_loc_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, gmem_load_loc_empty_n)
    begin
        if ((not(((gmem_load_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_load_loc_read <= ap_const_logic_1;
        else 
            gmem_load_loc_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_lookup_and_insert_fu_280_ap_start <= grp_lookup_and_insert_fu_280_ap_start_reg;
    grp_nbreadreq_fu_124_p3 <= (0=>(chunk_arr_stream_empty_n), others=>'-');

    hash_table_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state2, grp_lookup_and_insert_fu_280_hash_table_address0, p_cast_i_i_fu_310_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hash_table_address0 <= p_cast_i_i_fu_310_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            hash_table_address0 <= grp_lookup_and_insert_fu_280_hash_table_address0;
        else 
            hash_table_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    hash_table_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state2, grp_lookup_and_insert_fu_280_hash_table_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hash_table_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            hash_table_ce0 <= grp_lookup_and_insert_fu_280_hash_table_ce0;
        else 
            hash_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash_table_d0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state2, grp_lookup_and_insert_fu_280_hash_table_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hash_table_d0 <= ap_const_lv33_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            hash_table_d0 <= grp_lookup_and_insert_fu_280_hash_table_d0;
        else 
            hash_table_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hash_table_we0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state2, grp_lookup_and_insert_fu_280_hash_table_we0, exitcond386_i_i_fu_304_p2)
    begin
        if (((exitcond386_i_i_fu_304_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            hash_table_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            hash_table_we0 <= grp_lookup_and_insert_fu_280_hash_table_we0;
        else 
            hash_table_we0 <= ap_const_logic_0;
        end if; 
    end process;

    hit_fu_395_p1 <= grp_lookup_and_insert_fu_280_ap_return_1;
    i_2_cast_i_i_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_reg_245),64));
    i_4_fu_431_p2 <= std_logic_vector(unsigned(i_3_reg_268) + unsigned(ap_const_lv32_1));
    i_cast_i_i_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_234),64));
    icmp_ln179_fu_366_p2 <= "1" when (unsigned(i_3_reg_268) < unsigned(gmem_load_loc_read_reg_437)) else "0";
    icmp_ln58_fu_321_p2 <= "1" when (i_reg_234 = ap_const_lv6_20) else "0";
    icmp_ln64_fu_341_p2 <= "1" when (i_2_reg_245 = ap_const_lv7_40) else "0";

    internal_ap_ready_assign_proc : process(chunk_arr_stream_empty_n, codeword_stream_full_n, grp_nbreadreq_fu_124_p3, ap_CS_fsm_state8, tmp_i_i_reg_466, icmp_ln179_fu_366_p2, ap_predicate_op81_read_state8, ap_predicate_op87_write_state8)
    begin
        if ((not((((codeword_stream_full_n = ap_const_logic_0) and (ap_predicate_op87_write_state8 = ap_const_boolean_1)) or ((chunk_arr_stream_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state8 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and ((tmp_i_i_reg_466 = ap_const_lv1_0) or ((icmp_ln179_fu_366_p2 = ap_const_lv1_0) or (grp_nbreadreq_fu_124_p3 = ap_const_lv1_0))))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    nextCode_1_fu_411_p2 <= std_logic_vector(unsigned(nextCode_fu_114) + unsigned(ap_const_lv32_1));
    p_cast_i_i_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_223),64));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln172_fu_403_p1 <= grp_lookup_and_insert_fu_280_ap_return_0(16 - 1 downto 0);
    trunc_ln179_fu_387_p1 <= nextCode_fu_114(12 - 1 downto 0);
    trunc_ln183_fu_374_p1 <= p_0_fu_110(12 - 1 downto 0);
    trunc_ln_fu_378_p3 <= (trunc_ln183_fu_374_p1 & chunk_arr_stream_dout);
    zext_ln172_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(chunk_arr_stream_dout),16));
    zext_ln183_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_2_reg_499),16));
end behav;
