catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project mmult_fpga
set_top mmult_fpga
# v++ -g, -D, -I, --advanced.prop kernel.mmult_fpga.kernel_flags
add_files "/mnt/castor/seas_home/s/songqij/ese532_code/hw6/apps/mmult/fpga/hls/MMult.cpp" -cflags " -g -I /mnt/castor/seas_home/s/songqij/ese532_code/hw6/apps/mmult/fpga/hls "
open_solution -flow_target vitis solution
set_part xczu3eg-sbva484-1-i
create_clock -period 150.000000MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname mmult_fpga
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
